# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [12]:
import numpy as np
import itertools
def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def argument(txt, error):
    """
    The function cheks the entered data (n - int and n > 0 )
    """
    n = input(txt)
    try:
        n = int(n)
        if n <= 0:
            raise (error)
    except :
        print(error)
        n = argument("Введіть число: ","Ввести можна лише числа.")
    return n


a = argument("Введіть порядок матриці: ", "Ввести можна лише числа(n > 0).")
print(random_matrix(a))
print(np.linalg.det(random_matrix(a)))


[[9 8 2]
 [9 3 3]
 [9 9 1]]
102.00000000000004
